version: "3.7"

services:
  tests:
    build:
      dockerfile: dev.dockerfile
      context: .
    command: make test-ci
    container_name: tests
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: club_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vas3k_club
    ports:
      - 5432
